In [1]:
import tensorflow as tf

In [5]:
hello = tf.constant("hello world")

In [6]:
sess = tf.Session()

AttributeError: module 'tensorflow' has no attribute 'Session'

In [7]:
print(sess.run(hello))

NameError: name 'sess' is not defined

In [8]:
print(tf.__version__)

2.18.0


In [2]:
import numpy as np

In [4]:
mylist =  [1,2,3] #klasicna python lista
#numpy array
np.array(mylist)


array([1, 2, 3])

In [7]:
nested_list = [[1,2],[3,4], [5,6]]
np.array(nested_list) # kreira matricu 3x2 tj. dvodimenzionalnu matricu

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
np.arange(0,10) #kreiranje niza (start, stop, korak)
np.arange(0,10,2) # kreira niz od 0 do 10 sa korakom 2
np.zeros(3) # kreira niz od 3 elementa sa nulama
np.zeros((3,3)) # kreira matricu 3x3 redovi x kolone
np.ones(3)  #kreira vektor jedinica
np.ones((3,3))  #kreira matricu 3x3
np.linspace(0,10,3) #vraca broj elemenata ravnopravno rasporedjenih, primer: izmedju 0 i 10 vratice 3 elementa izmedju 0 i 10 sa jednakim razmakom ukljucujuci i krajnju vrednost
#linspace - linear space izmedju tacaka
np.eye(4) # vraca matricu sa nulama svuda osim na glavnoj dijagonali gde su jedinice

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
#Generisanje random stvari u NumPy
np.random.rand(2) #vraca 2 random broja sa uniformnom distribucijom izmedju 0 i 1
np.random.rand(3,4) #vraca matricu izmedju 0 i 1 3x4 uniformno distribucijom
np.random.randn(3,3) #vraca normalno distribuisanu sa srednjom vrednoscu 0 i varijansom 1
np.random.randint(0,100,10) #lowest vrednost(moguce da bude izabrana), highest vrednost(nije moguce da bude izabrana) i broj brojeva
np.random.seed(42)  #seed sa brojem 42 ce uvek kada se pokrene generisati iste brojeve
np.random.rand(4,4) #svaki put ce dati istu vrednost

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451]])

In [27]:
arr = np.arange(25)

In [31]:
ranarr = np.random.randint(0,50,10) 

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
ranarr

array([46, 43,  2, 36,  6, 20,  8, 38, 17,  3], dtype=int32)

In [34]:
arr.shape   #kaze da ima samo niz od 25 brojeva

(25,)

In [35]:
arr.reshape(5,5) #menja joj izgled tj. oblik u 5x5 matricu, ali ne menja originalan objekat arr
#ako se pokusa da se nesto reshape na 3x6 sa 5x5 dobice se greska jer se nema mesta za sve elemente

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
ranarr.max() #vraca maximalan element
ranarr.argmax()  #vraca index najveceg elementa
ranarr.argmin() #vraca index najmanjeg elementa

np.int64(0)

In [3]:
arr = np.arange(0,11) #kreira niz od 0 do 10
arr[8] #vraca element na indexu 8
arr[:5] #vraca niz od 0 indexa do 5 indexa ako je [:5] krece od pocetka do 5. indexa
arr[5:] #vraca od 5 indexa do kraja

array([0, 1, 2, 3, 4])

In [4]:
arr[0:5] = 100

In [5]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
print(arr_2d)
print(arr_2d.shape)
print(arr_2d[0])

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
(3, 3)
[ 5 10 15]


In [15]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
print(arr_2d[0,2])  #vadimo red, kolona
arr_2d[:2,1:]   #vratice na matricu 2x2, tako sto prvi parametar vraca prva dva reda (bez indexa 2), a drugi parametar vraca (kolone od 1 pa do kraja)

15


array([[10, 15],
       [25, 30]])

In [22]:
#Conditional selecting
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr > 4 #Vraca niz boolean vrednosti u kojima kaze gde su vrednosti vece od 4
bool_arr = arr > 4  
print(bool_arr)
arr[bool_arr]   #Vraca niz gde su elementi sve vece od True

arr[arr>4]  #Ova sintaksa takodje radi

[False False False False  True  True  True  True  True  True]


array([ 5,  6,  7,  8,  9, 10])

In [32]:
arr = np.arange(0,10)
arr + 5
arr + arr 
arr * arr
arr - arr #Sve ove operacije rade
arr / arr
#Numpy ce dopustiti deljenje sa nulom. Vratice Warning i dace rezultat kao NaN ili inf (beskonacno)

C:\Users\Windows\AppData\Local\Temp\ipykernel_1840\2502121371.py:6: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [34]:
arr = np.arange(0,10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [36]:
arr.var() #Varijansa
arr.std() #Standardna devijacija

np.float64(2.8722813232690143)

In [45]:
arr_2d = np.arange(0,25).reshape(5,5)
arr_2d.sum(axis=0) #Ovo ce uraditi za svaki red operaciju sum, odnosno sabira svaku vrednost u redu i, pa redu i+1...
#Operation across row axis = 0, Operation across columns axis = 1

array([50, 55, 60, 65, 70])

In [41]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])